.set-tag: &set-tag
- |
  if [ -n "${CI_COMMIT_TAG}" ] ; then
    # If this build is from a git tag, use that as the docker tag.
    export TAG_SPECIFIC="${CI_COMMIT_TAG}"
  else
    # If this build is from a branch, use the name and sha as the
    # docker tag.
    export TAG_SPECIFIC="${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
  fi

manifest:
  image: golang:1.15.9-buster

  before_script:
  - *set-tag
  - apt-get update
  - apt-get install -y gettext-base

  script:
  - make SUFFIX=${TAG_SPECIFIC} manifests
  - 'curl --silent --show-error --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file deploy/bird-epic.yaml "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/manifest/0.0.1/bird-epic.yaml"'

  artifacts:
    paths:
    - ./*.yaml
    - ./*.sh
    - configlets/*
    - deploy/*.yaml

docker:
  image: docker:20.10.5
  services:
  - docker:20.10.5-dind

  before_script:
  - *set-tag
  - apk add make
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

  script:
  - make SUFFIX=${TAG_SPECIFIC} GITLAB_USER=gitlab-ci-token GITLAB_PASSWORD=${CI_JOB_TOKEN} install
