apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-egw
  namespace: bird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-egw
  template:
    metadata:
      labels:
        app: bird-egw
    spec:
      containers:
      - name: bird-egw
        image: bird-egw:2.0.7
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
      hostNetwork: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
