apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-egw
  namespace: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-egw
  template:
    metadata:
      labels:
        app: bird-egw
    spec:
      containers:
      - name: bird-egw
        env:
        - name: BIRD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: BIRD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: BIRD_ML_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.gitlab.com/acnodal/egw-router/bird-egw:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 250Mi
          requests:
            memory: 250Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
        volumeMounts:
        - name: birdconfig
          mountPath: /usr/local/include/bird
        - name: bird-cm
          mountPath: /usr/local/etc
      imagePullSecrets:
      - name: gitlab
      volumes:
      - name: birdconfig
        persistentVolumeClaim:
          claimName: birdconfigvol
      - name: bird-cm
        configMap:
          name: bird-cm
      hostNetwork: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
---      
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: birdconfigvol
  namespace: router
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
